"use client";
import { useState } from "react";
import { analyzeMedicalReport } from "@/lib/actions";
import { saveReportToDb } from "@/lib/db"; // Import the helper
import { useAuth } from "@/lib/AuthContext"; // Import auth hook
import { Loader2, FileText, CheckCircle, AlertTriangle } from "lucide-react";

export default function SimplifyPage() {
  const { user } = useAuth();
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleForm(formData: FormData) {
    if (!user) return alert("Please sign in first.");

    setLoading(true);
    try {
      const file = formData.get("file") as File;
      const analysis = await analyzeMedicalReport(formData);

      setResult(analysis);

      // Save the analysis to the database
      if (analysis && !analysis.includes("I'm sorry")) {
        await saveReportToDb(user.uid, file.name, analysis);
      }
    } catch (err) {
      setResult("Error: Could not process the file.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12">
      <header className="mb-10">
        <h1 className="text-3xl font-bold text-slate-900">Report Simplifier</h1>
        <p className="text-slate-500 mt-2">
          Upload your lab results for a plain-English explanation.
        </p>
      </header>

      <form action={handleForm} className="mb-10">
        <div className="border-2 border-dashed border-blue-200 p-12 rounded-[2.5rem] text-center bg-white hover:border-blue-400 transition-all cursor-pointer relative group">
          <input
            type="file"
            name="file"
            accept="image/*,application/pdf"
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
            required
          />
          <div className="flex flex-col items-center">
            <div className="bg-blue-50 p-5 rounded-full text-blue-600 mb-4 group-hover:scale-110 transition-transform">
              <FileText size={32} />
            </div>
            <p className="text-slate-700 font-semibold">
              Click to upload or drag and drop
            </p>
            <p className="text-slate-400 text-sm mt-1">
              Supports PDF, PNG, and JPG
            </p>
          </div>
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full mt-6 bg-blue-600 text-white py-4 rounded-2xl font-bold hover:bg-blue-700 disabled:bg-slate-300 transition-all shadow-lg shadow-blue-100 flex items-center justify-center gap-2"
        >
          {loading ? (
            <Loader2 className="animate-spin" />
          ) : (
            "Simplify My Report"
          )}
        </button>
      </form>

      {result && (
        <div className="bg-white border border-slate-100 p-8 rounded-[2.5rem] shadow-xl shadow-slate-200/50">
          <div className="flex items-center gap-2 text-green-600 mb-6 font-bold bg-green-50 w-fit px-4 py-2 rounded-full text-sm">
            <CheckCircle size={18} /> Analysis Complete
          </div>

          <div className="prose prose-slate max-w-none whitespace-pre-wrap text-slate-700 leading-relaxed">
            {result}
          </div>

          <div className="mt-10 p-5 bg-amber-50 border border-amber-100 rounded-2xl flex gap-3 text-amber-800 text-sm italic">
            <AlertTriangle size={20} className="shrink-0" />
            <p>
              CareCompass is an educational tool. This summary is generated by
              AI and is not a medical diagnosis.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
