import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";

export default async function EmergencyPublicPage({
  params,
}: {
  params: { uid: string };
}) {
  const snap = await getDoc(doc(db, "emergency_profiles", params.uid));

  const data = snap.exists() ? snap.data() : null;

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center text-center">
        Emergency profile not found.
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-red-50 p-6">
      <div className="bg-white shadow-xl rounded-3xl p-8 max-w-md w-full border border-red-200">

        <h1 className="text-2xl font-bold text-red-600 mb-6">
          🚑 Emergency Health Card
        </h1>

        <div className="space-y-3 text-sm">

          <p><b>Name:</b> {data.name}</p>
          <p><b>Blood Group:</b> {data.bloodGroup}</p>
          <p><b>Allergies:</b> {data.allergies}</p>
          <p><b>Conditions:</b> {data.conditions}</p>
          <p><b>Medications:</b> {data.medications}</p>
          <p><b>Emergency Contact:</b> {data.contact}</p>

        </div>

        <p className="text-xs text-gray-500 mt-6">
          Generated by CareCompass
        </p>

      </div>
    </div>
  );
}